version: "3.7"

services:

  h2-proxy:
    # Don't use this proxy in prod
    build: ./docker/dev/h2-proxy
    container_name: app-proxy
    depends_on:
      - nginx
    ports:
      - "80:80"
      - "443:443"

  nginx:
    build:
      context: ./docker/dev/nginx
      dockerfile: Dockerfile
      args:
        MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
    container_name: app-nginx
    ports:
      - "8081:80"
    volumes:
      - ./app/public:/usr/srv/app/public:ro
    depends_on:
      - php-fpm
      - pgsql

  php-fpm:
    build: ./docker/dev/php/7.3/fpm
    container_name: app-php
    volumes:
      - ./app:/usr/srv/app:rw,cached
    depends_on:
      - pgsql

  php-cli:
    build: ./docker/dev/php/7.3/cli
    container_name: app-cli
    volumes:
      - ./app:/usr/srv/app:rw,cached
      - app-composer:/root/.composer/cache
    depends_on:
      - pgsql
    tty: true

  pgsql:
    image: postgres:12-alpine
    container_name: app-db
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-symfonist}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_LOCAL_PORT:-54321}:5432"

volumes:
  app-db-data:
  app-composer:
