version: "3.7"

services:
  
  sf4d-h2-proxy:
    # Don't use this proxy in prod
    build: 
      context: ./
      dockerfile: docker/dev/h2-proxy/Dockerfile
    container_name: sf4d-h2-proxy
    hostname: sf4d-h2-proxy
    depends_on:
      - sf4d-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./volumes/$APP_NAME/http2-proxy:/var/log/nginx"

  sf4d-nginx:
    build:
      context: ./
      dockerfile: docker/dev/nginx/Dockerfile
      args:
        WORKDIR: ${WORKDIR:-var/www}
        APP_NAME: ${APP_NAME:-app.test}
    container_name: sf4d-nginx
    hostname: sf4d-nginx
    restart: on-failure
    depends_on:
      - sf4d-php-fpm
    ports:
      - "${NGINX_LOCAL_PORT:-81}:80"
    volumes:
      - "./apps/$APP_NAME/public:/${WORKDIR}/${APP_NAME}/public"
      - "./volumes/$APP_NAME/nginx/logs:/var/log/nginx:rw"

  sf4d-php-fpm:
    build:
      context: ./
      dockerfile: docker/dev/php/7.3/fpm/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE:-UTC}
        WORKDIR: ${WORKDIR:-var/www}
        APP_NAME: ${APP_NAME:-app.test}
    container_name: sf4d-php-fpm
    hostname: sf4d-php-fpm
    volumes:
      - "./apps/$APP_NAME:/$WORKDIR/$APP_NAME"
      - "./volumes/$APP_NAME/php/var/cache:/$WORKDIR/$APP_NAME/var/cache:rw"
      - "./volumes/$APP_NAME/php/var/sessions:/$WORKDIR/$APP_NAME/var/sessions:rw"
      - "./volumes/$APP_NAME/php/var/logs:/$WORKDIR/$APP_NAME/var/logs:rw"
    depends_on:
      - sf4d-db
      - sf4d-redis
    #user: ${LOCAL_USER}

  sf4d-php-cli:
    build:
      context: ./
      dockerfile: docker/dev/php/7.3/cli/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE:-UTC}
        WORKDIR: ${WORKDIR:-var/www}
        APP_NAME: ${APP_NAME:-app.test}
    container_name: sf4d-php-cli
    hostname: sf4d-php-cli
    volumes:
      - ./apps/$APP_NAME:/$WORKDIR/$APP_NAME
      - composer:/root/.composer/cache:rw
    links:
      - sf4d-db
      - sf4d-redis
    #user: ${LOCAL_USER}
    tty: true

  sf4d-db:
    image: postgres:11.2-alpine
    container_name: sf4d-db
    hostname: sf4d-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-symfonist}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
    ports:
      - "${POSTGRES_LOCAL_PORT:-54321}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  sf4d-adminer:
    image: adminer
    container_name: sf4d-adminer
    hostname: sf4d-adminer
    restart: always
    links:
      - sf4d-db
    ports:
      - '${ADMINER_LOCAL_PORT:-8080}:8080'

  sf4d-redis:
    image: redis:5-alpine
    container_name: sf4d-redis
    hostname: sf4d-redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command:
      - 'redis-server'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--requirepass secret'

volumes:
  db-data:
  redis:
  composer:
